### ISSUE TITLE
Es1 review

### ISSUE THREAD

**Issue by Marco-Masera** [jonathan2503/Computational_intelligences_301514#1]
Hi. I leave the review for your Lab1.

## Well written and readable greedy solution.
You decided for a greedy solution, and the one you implemented is very compact and well written. I personally learned a few features of python reading your code.
The heuristic you used to choose which node to expand is good. 
If you choose instead to implement a beam search the result would probably be much closer to the optimal, but this is probably just a choice of implementation.

## Criticism
To be honest I have a hard time finding criticism here but I found a few things:
* The nodes visited print at the end of the algorithm is a little misleading because the actual number of nodes visited is equal to the number of iterations, while you are counting (Number_Of_Iterations)*(Number_Of_Lists), probably because the max() function has linear time to the size of the list.
* In order to reduce time you could have decided to keep the lists inside a set and, at each iteration, remove from it the list used, so that it won't be tested again.
* The **lengths** list is not useful as you could simply use len() on the set, since you never modify the original lists.

## Conclusion
It is a well written greedy algorithm with close to no iusses.

**Comment by jonathan2503** [comment]
## Acknowledgements  
kindest Marco Masera, I would like to sincerely thank you for spending time to review my project, I appreciated the criticism and will try to implement your suggestions in my code as soon as I can.
## conclusion 
I am not closing this issue because I wish to make the changes you suggested, as soon as I make them if you have time I would appreciate it if you would view them

## Best regards
If you then also have some time I would be very happy if you visit my projects and research: 
<a href="https://github.com/jonathan2503"><img src="https://img.shields.io/badge/-Jonathan%20Damone-181717?style=flat&logo=github&logoColor=white"/></a>
<a href="https://www.researchgate.net/profile/Jonathan-Damone"><img src="https://img.shields.io/badge/-Jonathan%20Damone-00CCBB?style=flat&logo=ResearchGate&logoColor=white"/></a>
feel free to contact me if you would like to collaborate on research or to discuss emerging issues.
kind regards
Jonathan Damone

**Comment by jonathan2503** [comment]
# Conclusion
improved performance of time and number of nodes thanks to the suggestion.
